// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zipkin/proto3/zipkin.proto

package zipkin2.proto3;

public final class Zipkin {
  private Zipkin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zipkin_proto3_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zipkin_proto3_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zipkin_proto3_Span_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zipkin_proto3_Span_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zipkin_proto3_Endpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zipkin_proto3_Endpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zipkin_proto3_Annotation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zipkin_proto3_Annotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zipkin_proto3_ListOfSpans_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zipkin_proto3_ListOfSpans_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zipkin_proto3_ReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zipkin_proto3_ReportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032zipkin/proto3/zipkin.proto\022\rzipkin.pro" +
      "to3\"\365\003\n\004Span\022\020\n\010trace_id\030\001 \001(\014\022\021\n\tparent" +
      "_id\030\002 \001(\014\022\n\n\002id\030\003 \001(\014\022&\n\004kind\030\004 \001(\0162\030.zi" +
      "pkin.proto3.Span.Kind\022\014\n\004name\030\005 \001(\t\022\021\n\tt" +
      "imestamp\030\006 \001(\006\022\020\n\010duration\030\007 \001(\004\022/\n\016loca" +
      "l_endpoint\030\010 \001(\0132\027.zipkin.proto3.Endpoin" +
      "t\0220\n\017remote_endpoint\030\t \001(\0132\027.zipkin.prot" +
      "o3.Endpoint\022.\n\013annotations\030\n \003(\0132\031.zipki" +
      "n.proto3.Annotation\022+\n\004tags\030\013 \003(\0132\035.zipk" +
      "in.proto3.Span.TagsEntry\022\r\n\005debug\030\014 \001(\010\022" +
      "\016\n\006shared\030\r \001(\010\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"U\n\004Kind\022\031\n\025SPAN_KIN" +
      "D_UNSPECIFIED\020\000\022\n\n\006CLIENT\020\001\022\n\n\006SERVER\020\002\022" +
      "\014\n\010PRODUCER\020\003\022\014\n\010CONSUMER\020\004\"J\n\010Endpoint\022" +
      "\024\n\014service_name\030\001 \001(\t\022\014\n\004ipv4\030\002 \001(\014\022\014\n\004i" +
      "pv6\030\003 \001(\014\022\014\n\004port\030\004 \001(\005\".\n\nAnnotation\022\021\n" +
      "\ttimestamp\030\001 \001(\006\022\r\n\005value\030\002 \001(\t\"1\n\013ListO" +
      "fSpans\022\"\n\005spans\030\001 \003(\0132\023.zipkin.proto3.Sp" +
      "an\"\020\n\016ReportResponse2T\n\013SpanService\022E\n\006R" +
      "eport\022\032.zipkin.proto3.ListOfSpans\032\035.zipk" +
      "in.proto3.ReportResponse\"\000B\022\n\016zipkin2.pr" +
      "oto3P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zipkin_proto3_Span_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zipkin_proto3_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zipkin_proto3_Span_descriptor,
        new java.lang.String[] { "TraceId", "ParentId", "Id", "Kind", "Name", "Timestamp", "Duration", "LocalEndpoint", "RemoteEndpoint", "Annotations", "Tags", "Debug", "Shared", });
    internal_static_zipkin_proto3_Span_TagsEntry_descriptor =
      internal_static_zipkin_proto3_Span_descriptor.getNestedTypes().get(0);
    internal_static_zipkin_proto3_Span_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zipkin_proto3_Span_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_zipkin_proto3_Endpoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zipkin_proto3_Endpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zipkin_proto3_Endpoint_descriptor,
        new java.lang.String[] { "ServiceName", "Ipv4", "Ipv6", "Port", });
    internal_static_zipkin_proto3_Annotation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_zipkin_proto3_Annotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zipkin_proto3_Annotation_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
    internal_static_zipkin_proto3_ListOfSpans_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_zipkin_proto3_ListOfSpans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zipkin_proto3_ListOfSpans_descriptor,
        new java.lang.String[] { "Spans", });
    internal_static_zipkin_proto3_ReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_zipkin_proto3_ReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zipkin_proto3_ReportResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
